site_name: mathnotes-measure_theory
site_author: qiulinfan
site_url: https://github.com/qiulinfan/mathnotes-measure_theory
use_directory_urls: false
remote_branch: gh-deploy

repo_name: mathnotes-measure_theory
repo_url: https://github.com/qiulinfan/mathnotes-measure_theory

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - tables
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Chapters:
    - 01-sigma-algebra-与-measure: 01-sigma-algebra-与-measure.md
    - hw01-on_sigma-algebra: hw01-on_sigma-algebra.md
    - 02-outer-measure-与-completion-of-a-measurable-space: 02-outer-measure-与-completion-of-a-measurable-space.md
    - hw02-on_Carathéodorys&Hahn-Kolmogrov-thm: hw02-on_Carathéodorys&Hahn-Kolmogrov-thm.md
    - 03-distribution-function-与-lebesgue-stieltjes-measures: 03-distribution-function-与-lebesgue-stieltjes-measures.md
    - hw03-on_Lebesgue-Stieljes-measures: hw03-on_Lebesgue-Stieljes-measures.md
    - 04-measurable_functions_and_integration_on_L^+(mu): 04-measurable_functions_and_integration_on_L^+(mu).md
    - hw04-on_measurable-functions: hw04-on_measurable-functions.md
    - 05-integration_of_real_and_complex_functions: 05-integration_of_real_and_complex_functions.md
    - hw05-on_integration: hw05-on_integration.md
    - 06-product_measure&Fubini-Tonelli: 06-product_measure&Fubini-Tonelli.md
    - hw06-on_product-measure&mode-of-convergence: hw06-on_product-measure&mode-of-convergence.md
    - 07-Lebesgue_measure_on_R^n: 07-Lebesgue_measure_on_R^n.md
    - 08-Hardy-Littlewood&LDT: 08-Hardy-Littlewood&LDT.md
    - hw07-on_differentiaion: hw07-on_differentiaion.md
    - 09-L^P-space_and_inequalities: 09-L^P-space_and_inequalities.md
    - hw08-on_L^p-spacecs: hw08-on_L^p-spacecs.md
    - 10-signed_measure&Jordan-decomposition: 10-signed_measure&Jordan-decomposition.md
    - hw09-on_signed-measure: hw09-on_signed-measure.md
    - 11-Radon-Nikodym_theorem: 11-Radon-Nikodym_theorem.md
    - hw10-on_LRN-theorem&complex-measure: hw10-on_LRN-theorem&complex-measure.md
    - 12-differentiation_on_real_spaces: 12-differentiation_on_real_spaces.md
    - hw11-on_regular-borel-measure&BV: hw11-on_regular-borel-measure&BV.md
    - hw12-on_absolutely-continuous-functions: hw12-on_absolutely-continuous-functions.md
    - 13-the_dual_of_L^p-spaces: 13-the_dual_of_L^p-spaces.md
